# Generated by Django 3.0.6 on 2020-07-05 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardapp', '0006_auto_20200628_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='is_publoc',
            new_name='is_public',
        ),
    ]
